title: Data Science Notes
description: Machine Learning<br>Computer Vision<br>Programming<br>Visualizations<br>Applications

baseurl: ""
url: ""
github_username: zoowirt
author: Martin Meyries
location: Karlsruhe, Germany
company: dataqube GmbH
company_url: https://www.dataqube.de/
skin: daylight

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton