title: Data Science Notebook
description: >- # this means to ignore newlines until "baseurl:"
  Notes on Data Science, Computer Vision, Programming, Visualization and Applications

github_username: zoowirt
author: Martin Meyries
location: Karlsruhe, Germany
company: dataqube GmbH
company_url: https://www.dataqube.de/
skin: daylight

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton
